[package]
name = "pest-example"
version = "0.1.0"
authors = ["zhangchunzhong <zczxyz@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "^1.0"
pest_derive = "^1.0"